### ISSUE TITLE
error: could not find wasm-opt, set the WASMOPT environment variable to override (macOS runner)

### ISSUE THREAD

**Issue by Integralist** [acifani/setup-tinygo#2]
👋🏻 I've been trying to use this action but finding that I get the following error on the macOS runner:

```
error: could not find wasm-opt, set the WASMOPT environment variable to override
```

I then found this tinygo issue: https://github.com/tinygo-org/tinygo/issues/2319 which suggests:

```
brew install binaryen wasm-tools
```

But looks like even though these two packages install fine, I still get the error.

Any ideas on how to resolve this issue? 

Thanks!

**Comment by Integralist** [comment]
**UPDATE**: I'm also seeing this error with the Windows runner.

**Comment by acifani** [comment]
Hey @Integralist, sorry for the late response. I see you have found a workaround, great! I would happily merge it upstream or try to fix it myself if you can send me a reproducible build that fails

**Comment by Integralist** [comment]
Thanks for getting back to me 🙂

I probably wouldn't take my changes verbatim as I hacked it together due to time constraints. 

So maybe just use my implementation as inspiration.

**Comment by ca1e** [comment]
same erro when use tinygo with `scoop install tinygo`

**Comment by Integralist** [comment]
@ca1e if you're in a rush you can use https://github.com/Integralist/setup-tinygo

**Comment by ca1e** [comment]
no worry! I just fixed it by run `scoop install binaryen` manually

**Comment by Integralist** [comment]
Yeah I did the same back when I wasn't using a custom action. But I wanted an action because when I was manually setting up tinygo via scoop for Windows I was having a problem persisting the tinygo binary to another step that required it. I just couldn't get it added to the path so it would be persisted. But via the custom action it was much easier.

**Comment by acifani** [comment]
@ca1e @Integralist I've released [v1.1.0](https://github.com/acifani/setup-tinygo/releases/tag/v1.1.0) with Binaryen included. Thanks for the report and please do let me know if you run into anything else!
